M48
; DRILL file {KiCad 8.0.4+dfsg-1} date 2025-02-17T17:51:02+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-17T17:51:02+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1083
%
G90
G05
T1
X3.2283Y-3.6614
X3.2283Y-4.5669
X5.5118Y-3.6614
X5.5118Y-4.5669
M30
